name: wms
description: "Warehouse Management System (WMS) by Vacalvers"
author: "Vacalvers"
publish_to: 'none'
homepage: 'https://vacalvers.com'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # --- UI / Styling ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  loading_indicator: ^3.1.1
  audioplayers: ^6.0.0
  # --- State / Routing ---
  get: ^4.6.6

  # --- Local Storage / System Info ---
  shared_preferences: ^2.3.1
  package_info_plus: ^8.0.0
  battery_plus: ^6.1.1
  connectivity_plus: ^6.1.3
  permission_handler: ^11.3.1

  # --- Network / APIs ---
  http: ^1.2.2

  # --- Sharing / Links ---
  share_plus: ^10.0.2
  url_launcher: ^6.3.0

  # --- QR / Scanner (NEW, modern & smooth) ---
  mobile_scanner: ^3.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/deodap_logo.png
    - assets/sammy-line-shopping.gif
    - assets/onboarding_one.gif
    - assets/onboarding_three.gif
    - assets/whatsapp_image.png
    - assets/facebook_image.png
    - assets/linkdin_image.png
    - assets/snapchat_image.png
    - assets/youtube_image.png
    - assets/instagram_image.png
    - assets/map.png
    - assets/success.mp3
    - assets/siren.mp3
    - assets/login.png
    - assets/qr.png