name: amz
description: "A amz DD return ++"
publish_to: 'none'
version: 1.1.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: any
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.4
  flutter_animate: ^4.5.0
  lottie: ^3.3.0
  # Networking & APIs
  http: ^1.2.2
  cached_network_image: ^3.3.1  # Or latest version
  dio: ^5.7.0
  get: ^4.6.6
  http_parser: ^4.0.0
  url_launcher: ^6.2.5
  share_plus: any
  connectivity_plus: any
  flutter_cache_manager: ^3.3.0
  # Storage & Utilities
  shared_preferences: any
  path_provider: ^2.1.2
  package_info_plus: any
  permission_handler: any
  flutter_native_splash: any

  # Media & Image Handling
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  crop_your_image: ^2.0.0
  gal: ^2.3.0  # gallery_saver નો alternative

  animated_background: ^2.0.0
  loading_indicator: ^3.1.1
  awesome_dialog: ^3.2.1
  dotted_border: ^2.0.0+2  # Supports borderType
  pinput: ^5.0.0

  # Scanner & Timer
  mobile_scanner: ^7.0.1
  flutter_countdown_timer: ^4.1.0

  # Excel/Exporting
  excel: ^4.0.6
  syncfusion_flutter_xlsio: any
  flutter_image_compress: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/lanchure_icon.png"

flutter_native_splash:
  android: false
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/icons/launchere_icon.png
    - assets/images/
    - assets/images/dd.png
    - assets/images/launcher_icon.png
    - assets/images/splachscreen_image.png
