name: calllogmonitor
description: A Flutter app to monitor call logs with SIM card detection.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0
  # Core Features
  http: ^1.2.1
  shared_preferences: ^2.2.2
  call_log: ^6.0.0
  intl: ^0.18.1
  telephony: ^0.2.0
  image_picker: ^1.0.4
  permission_handler: ^11.3.0
  font_awesome_flutter: ^10.0.0
  # Background Services
  flutter_background: ^1.0.9
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.2.2
  flutter_animate: ^4.2.0+1

  # Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.2

  # Device Info
  device_info_plus: ^10.1.0
  package_info_plus: ^4.2.0
  path: ^1.8.3
  google_fonts: ^6.2.1 
  # Connectivity & System
  connectivity_plus: ^5.0.2
  battery_plus: ^4.0.2
  android_intent_plus: ^4.0.2
  url_launcher: ^6.2.4
  fl_chart: ^0.64.0
  # Optional (for calls)
  flutter_callkit_voximplant: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/deodap_logo.png
    - assets/home_screen.png
    - assets/onboarding_screen_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/home_screen.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/deodap_logo.png"
